[ananke]
show_recent_posts = true

[ananke.home]
content_alignment = "right"

[ananke.social]
icon_path = "ananke/socials/%s.svg"

[ananke.social.follow]
new_window_icon = false
networks = [
  "linkedin",
  "instagram",
  "github"
]

[ananke.social.share]
new_window_icon = false
networks = [
  "linkedin",
  "instagram"
]

[ananke.social.networks.linkedin]
name = "linkedin"
profile = "https://linkedin.com/in/rikferreira"

[ananke.social.networks.instagram]
name = "instagram"
profile = "https://instagram.com/rik.ferreira"

[ananke.social.networks.github]
name = "github"
profile = "https://github.com/RikFerreira"