baseURL = 'http://rikalves.com/'
locale = 'en-us'
title = 'Rik F. Alves'
theme = 'ananke'

[menu]

  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 2

  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 3