baseURL = 'http://rikalves.com/'
locale = 'en-us'
title = 'Rik F. Alves'
theme = 'ananke'

[menu]
    [[menu.main]]
        name = "Home"
        pageRef = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        pageRef = "/posts"
        weight = 2

    [[menu.main]]
        name = "Apps"
        pageRef = "/apps"
        weight = 3

    [[menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 4

[params]

[params.ananke_socials]
networks = ["github", "linkedin"]
socialInHeader = true
socialInFooter = true

[params.ananke.social.github]
username = "rikalves"
profilelink = "https://github.com/rikalves"

[params.ananke.social.linkedin]
username = "rik"
profilelink = "https://linkedin.com/in/rik"