baseURL = 'http://rikalves.com/'
locale = 'en-us'
title = 'Rik F. Alves'
theme = 'ananke'

[menu]
    [[menu.main]]
        name = "Home"
        pageRef = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        pageRef = "/posts"
        weight = 2

    [[menu.main]]
        name = "Apps"
        pageRef = "/apps"
        weight = 3

    [[menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 4

[params]
  description = "GIS Analyst"

[[params.social]]
name = "github"
url = "https://github.com/rikalves"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/yourprofile"